/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AuthProfileState {
  state_json: string;
  state_key: string;
  updated_at: number;
}

export interface AuthProfileStore {
  store_json: string;
  store_key: string;
  updated_at: number;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface MemoryChannelAtomSyncState {
  atom_id: string;
  chunk_hash: string;
  chunk_path: string;
  index_identity_hash: string;
  indexed_at: number;
}

export interface MemoryChannelAtoms {
  account_id: string | null;
  alias_of: string | null;
  authority: string;
  body: string;
  conversation_alias: string | null;
  conversation_id: string;
  id: string;
  ingested_at: number;
  message_id: string;
  migration_group_id: string | null;
  provider: string;
  received_at: number;
  sender_display_name: string | null;
  sender_handle: string | null;
  sender_id: string | null;
  surface: string;
  thread_id: string | null;
  thread_key: string;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: string;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunks {
  embedding: string;
  end_line: number;
  hash: string;
  id: string | null;
  model: string;
  path: string;
  source: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  key: string | null;
  value: string;
}

export interface MemoryIndexSources {
  hash: string;
  mtime: number;
  path: string;
  size: number;
  source: Generated<string>;
}

export interface MemoryIndexState {
  id: Generated<number>;
  revision: number;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface DB {
  auth_profile_state: AuthProfileState;
  auth_profile_store: AuthProfileStore;
  cache_entries: CacheEntries;
  memory_channel_atom_sync_state: MemoryChannelAtomSyncState;
  memory_channel_atoms: MemoryChannelAtoms;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  memory_index_state: MemoryIndexState;
  schema_meta: SchemaMeta;
}
